### ISSUE TITLE
Open EDQLs error

### ISSUE THREAD

**Issue by ljynfo** [chengpohi/elasticshell#24] opened 2023-03-31 05:57 UTC
Open EDQLs error

IDEA:2023.1
Pluguin:1.9.19

java.lang.NoSuchMethodError: 'com.intellij.openapi.fileEditor.impl.text.TextEditorComponent com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.getComponent()'
	at com.github.chengpohi.edql.editor.EDQLPsiAwareTextEditor.createComponent(EDQLPsiAwareTextEditor.java:89)
	at com.github.chengpohi.edql.editor.EDQLPsiAwareTextEditor.<init>(EDQLPsiAwareTextEditor.java:54)
	at com.github.chengpohi.edql.editor.EDQLTextFileEditorProvider.createEditor(EDQLTextFileEditorProvider.java:28)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.createComposite(FileEditorManagerImpl.kt:1139)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.doOpenInEdtImpl(FileEditorManagerImpl.kt:1048)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.doOpenInEdtImpl$default(FileEditorManagerImpl.kt:1035)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileImpl4$open$1.invoke(FileEditorManagerImpl.kt:1010)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$openFileImpl4$open$1.invoke(FileEditorManagerImpl.kt:996)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$Companion.runBulkTabChange$intellij_platform_ide_impl(FileEditorManagerImpl.kt:390)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4$open(FileEditorManagerImpl.kt:996)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4$intellij_platform_ide_impl(FileEditorManagerImpl.kt:1024)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2$lambda$22(FileEditorManagerImpl.kt:900)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.kt:899)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFile(FileEditorManagerImpl.kt:798)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl$lambda$31(FileEditorManagerImpl.kt:1275)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.kt:1268)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.kt:1245)
	at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:239)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInAnyFileEditor(FileNavigatorImpl.java:110)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.java:86)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.java:71)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.java:49)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:89)
	at com.github.chengpohi.dock.EDQLDockComponent$13.lambda$actionPerformed$0(EDQLDockComponent.java:299)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by chengpohi** [comment] 2023-04-01 13:44
Hi @ljynfo this is caused by 2023 version incompatiblity, it will fixed in 1.9.20 and release in this weekend

**Comment by chengpohi** [comment] 2023-04-02 12:04
Hi @ljynfo  , this incomatible issue is fixed in version [v1.9.20](https://github.com/chengpohi/edql/releases/tag/v1.9.20), if there is still has any issue pls let me know. thanks your feedback.

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [v1.9.20](https://github.com/chengpohi/edql/releases/tag/v1.9.20)

**Comment by ljynfo** [comment] 2023-04-03 02:02
> Hi @ljynfo , this incomatible issue is fixed in version [v1.9.20](https://github.com/chengpohi/edql/releases/tag/v1.9.20), if there is still has any issue pls let me know. thanks your feedback.
> 
> Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin: [v1.9.20](https://github.com/chengpohi/edql/releases/tag/v1.9.20)

Yi, thank you very match, the problem is not find when I reinstall 1.9.20.
Thank you, oh.

**Closed as completed** 2023-04-04 01:38 UTC
