### ISSUE TITLE
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by Muscleape** [chengpohi/elasticshell#44] opened 2024-07-15 12:39 UTC
Mac  M1  OS: 13.2.1   
IDEA:2024.1.4 (Ultimate Edition)  
pluginVersion:1.10.12

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.chengpohi.action.dock.EDQLDockComponent$buildConsoleAction$action$1' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.chengpohi]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by chengpohi** [comment] 2024-07-16 02:04
Hi @Muscleape , This error is caused by intellij incompatible change, but it's just a warning info.

I will remove the incompatible warning in next version. Thanks your feedback.

**Comment by chengpohi** [comment] 2024-08-21 03:41
Hi @Muscleape , this error is fixed by 1.0.13, you can download from Jetbrains market [v1.10.13](https://plugins.jetbrains.com/plugin/16364-elasticsearch-query--edql/edit/versions/stable/590601) or manual install by [v1.10.13](https://github.com/chengpohi/edql/releases/tag/v1.10.13)

**Closed as completed by chengpohi** 2024-08-21 03:41 UTC
Labels: bug
