### ISSUE TITLE
Not a JSON Object: "_all"

### ISSUE THREAD

**Issue by lubino** [chengpohi/elasticshell#21] opened 2023-03-09 09:32 UTC
After running simple query to get basic information about index: `GET name_of_the_index`

I receive error message about failed execution instead of the response:
`java.lang.IllegalStateException: Not a JSON Object: "_all"`
`	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)`
`	at com.github.chengpohi.util.JsonUtil.mapProps(JsonUtil.java:48)`
full message: [log.txt](https://github.com/chengpohi/edql/files/10929722/log.txt)

The response to that query from other tool:
[response.json.txt](https://github.com/chengpohi/edql/files/10929776/response.json.txt)

I don't know how to debug this plugin, but my suspicion is that extraordinary Opensearch response `"copy_to": [ "_all" ]` for almost each property.
Is it because plugin doesn't support this `copy_to` (array of strings) format in properties configuration?

**Comment by chengpohi** [comment] 2023-03-09 09:42
Got it, Thanks feedback, I will take a look at this issue.

**Comment by chengpohi** [comment] 2023-03-09 09:47
Hi @lubino currently you can use the right side EDQL doc manager and Index module to manager your index, it's a pure json editor will not fail when visulization.

**Comment by chengpohi** [comment] 2023-03-14 15:03
hi @lubino this issue is fixed in version [v1.9.19](https://github.com/chengpohi/edql/releases/tag/v1.9.19)
this issue is caused by `copy_to` field in mapping, copy_to field is array type, but I handle it as an object, so throw the type error.

Since Jetbrains still reviewing the new version, you can manually download, and reinstall plugin:  [v1.9.19](https://github.com/chengpohi/edql/releases/tag/v1.9.19)

![image](https://user-images.githubusercontent.com/5118048/225039279-50037506-a191-4595-8503-6f80b1e1888e.png)

**Closed as completed** 2023-03-15 05:02 UTC
Labels: bug
